version: '3'

services:
  app:
    build: .
    volumes:
      - "./:/app"
    command: bin/bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN_NAME=${MAILGUN_DOMAIN_NAME}
      - EXCEPTION_NOTIFIER_RECEIVER_EMAIL=${EXCEPTION_NOTIFIER_RECEIVER_EMAIL}
      - DATABASE_URL=${DATABASE_URL}
    stdin_open: true
    tty: true
